# Generated by Django 4.1.13 on 2024-10-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catagory',
            field=models.CharField(choices=[('Men', 'Men'), ('Female', 'Female')], max_length=50),
        ),
    ]
