# Generated by Django 4.1.13 on 2024-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_item_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catagory',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
